v2
VKCOM/icons pull request #286
Opened 2022-11-03 09:31 UTC by eugpoloz

Драфт для отслеживания изменений будущей v2 по сравнению с `master`.

2022-11-03 09:33 UTC, vkcom-publisher commented
## size-limit report 📦 
| Path                                             | Size                  |
| ------------------------------------------------ | --------------------- |
| JS                                               | 2.53 MB (-0.2% 🔽)    |
| JS (gzip)                                        | 678.96 KB (-0.14% 🔽) |
| JS (brotli)                                      | 497.29 KB (-0.09% 🔽) |
| JS ES6 with Icon16Add only import (tree shaking) | 4.51 KB (0%)          |
| SVG                                              | 2.92 MB (-0.2% 🔽)    |

2022-12-07 13:34 UTC, SevereCloud approved these changes

2022-12-07 13:40 UTC, SevereCloud requested changes

2022-12-07 13:40 UTC, SevereCloud commented on package.json
> +  "version": "2.0.0-alpha.3",
```suggestion
  "version": "1.209.0",
```

2022-12-07 13:40 UTC, SevereCloud commented on packages/icons-scripts/package.json
> +  "version": "1.0.0-alpha.3",
```suggestion
  "version": "0.8.4",
```

2022-12-07 13:47 UTC, SevereCloud approved these changes

2022-12-07 13:58 UTC, merged