feat: Добавить префиксы на className
VKCOM/icons pull request #96
Opened 2021-03-02 13:56 UTC by thoughtspile

В компанию к префиксам на классы в VKUI https://github.com/VKCOM/VKUI/pull/1380

Добавляет <IconSettings>, в котором можно настроить:
- `classPrefix="vkui"` -> `class="vkuiIcon vkuiIcon--size-16"`
- `globalClasses` -> `class="vkuiIcon Icon vkuiIcon--size-16 Icon--size-16"`, режим обратной совместимости

2021-03-03 07:20 UTC, fedorov-xyz requested changes

2021-03-03 07:20 UTC, fedorov-xyz commented on src/IconSettings.tsx
> +export const IconSettings: FC<IconSettingsInterface> = ({ children, ...settings }) => {
Предлагаю переименовать в `IconsSettingsProvider`, чтобы было более понятно, что этот компонент делает. Пока по названию похоже, что это компонент иконки настроек.

2021-03-04 06:35 UTC, fedorov-xyz commented on src/IconSettings.tsx
> +export const IconSettingsProvider: FC<IconSettingsInterface> = ({ children, ...settings }) => {
Название файла бы тоже под название компонента подогнать.

2021-03-04 09:13 UTC, thoughtspile commented on src/IconSettings.tsx
> +export const IconSettingsProvider: FC<IconSettingsInterface> = ({ children, ...settings }) => {
Ну не знаю, тут есть `Context`, `Provider` и `Interface`. Можно разнести на 2 файла, но они сильно связаны и я не уверен что будет лучше

2021-03-04 09:14 UTC, fedorov-xyz approved these changes

2021-03-05 10:39 UTC, merged